<?php

/**
 * @file
 * Install functions.
 */

/**
 * Update field from plain text to rich.
 */
function stanford_paragraph_filmstrip_update_8100() {
  // Common function included here.
  module_load_include('install', 'stanford_paragraph_types');

  // The field and db tables to changes.
  $fields = [
    'field_p_filmstrip_descriptor' => [
      'table' => 'paragraph__field_p_filmstrip_descriptor',
      'revision_table' => 'paragraph_revision__field_p_filmstrip_descriptor',
      'format_col' => 'field_p_filmstrip_descriptor_format',
      'value_col' => 'field_p_filmstrip_descriptor_value',
    ],
  ];

  // Change the DB tables and preserve the data.
  _stanford_paragraph_types_change_to_formatted($fields);

}
